//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptimaBaseForm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptPath {
            get {
                return ((string)(this["OptPath"]));
            }
            set {
                this["OptPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptUser {
            get {
                return ((string)(this["OptUser"]));
            }
            set {
                this["OptUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptPass {
            get {
                return ((string)(this["OptPass"]));
            }
            set {
                this["OptPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptCompany {
            get {
                return ((string)(this["OptCompany"]));
            }
            set {
                this["OptCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerKey {
            get {
                return ((string)(this["ServerKey"]));
            }
            set {
                this["ServerKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptModulyUsera {
            get {
                return ((bool)(this["OptModulyUsera"]));
            }
            set {
                this["OptModulyUsera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptKBP {
            get {
                return ((bool)(this["OptKBP"]));
            }
            set {
                this["OptKBP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptHAP {
            get {
                return ((bool)(this["OptHAP"]));
            }
            set {
                this["OptHAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BLToken {
            get {
                return ((string)(this["BLToken"]));
            }
            set {
                this["BLToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NazwaSerweraSql {
            get {
                return ((string)(this["NazwaSerweraSql"]));
            }
            set {
                this["NazwaSerweraSql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NazwaBazySql {
            get {
                return ((string)(this["NazwaBazySql"]));
            }
            set {
                this["NazwaBazySql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowsAuth {
            get {
                return ((bool)(this["WindowsAuth"]));
            }
            set {
                this["WindowsAuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SqlAuth {
            get {
                return ((bool)(this["SqlAuth"]));
            }
            set {
                this["SqlAuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginSql {
            get {
                return ((string)(this["LoginSql"]));
            }
            set {
                this["LoginSql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HasloSql {
            get {
                return ((string)(this["HasloSql"]));
            }
            set {
                this["HasloSql"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlOptBazaKonfigConnectionStr {
            get {
                return ((string)(this["SqlOptBazaKonfigConnectionStr"]));
            }
            set {
                this["SqlOptBazaKonfigConnectionStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SqlConnStringPobierajZOpt {
            get {
                return ((bool)(this["SqlConnStringPobierajZOpt"]));
            }
            set {
                this["SqlConnStringPobierajZOpt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OptIdAtrStatusZamOpt {
            get {
                return ((int)(this["OptIdAtrStatusZamOpt"]));
            }
            set {
                this["OptIdAtrStatusZamOpt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogPath {
            get {
                return ((string)(this["LogPath"]));
            }
            set {
                this["LogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteOldLogs {
            get {
                return ((bool)(this["DeleteOldLogs"]));
            }
            set {
                this["DeleteOldLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal DeleteOldLogsDays {
            get {
                return ((decimal)(this["DeleteOldLogsDays"]));
            }
            set {
                this["DeleteOldLogsDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompanyGID {
            get {
                return ((string)(this["CompanyGID"]));
            }
            set {
                this["CompanyGID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlConnectionString {
            get {
                return ((string)(this["SqlConnectionString"]));
            }
            set {
                this["SqlConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlConnectionStringFirma2 {
            get {
                return ((string)(this["SqlConnectionStringFirma2"]));
            }
            set {
                this["SqlConnectionStringFirma2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Opt2KonfigConnectStr {
            get {
                return ((string)(this["Opt2KonfigConnectStr"]));
            }
            set {
                this["Opt2KonfigConnectStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Opt2Operator {
            get {
                return ((string)(this["Opt2Operator"]));
            }
            set {
                this["Opt2Operator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Opt2Haslo {
            get {
                return ((string)(this["Opt2Haslo"]));
            }
            set {
                this["Opt2Haslo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Opt2Firma {
            get {
                return ((string)(this["Opt2Firma"]));
            }
            set {
                this["Opt2Firma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptPassword {
            get {
                return ((string)(this["OptPassword"]));
            }
            set {
                this["OptPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptKBPFirma2 {
            get {
                return ((bool)(this["OptKBPFirma2"]));
            }
            set {
                this["OptKBPFirma2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptHAPFirma2 {
            get {
                return ((bool)(this["OptHAPFirma2"]));
            }
            set {
                this["OptHAPFirma2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptPathFirma2 {
            get {
                return ((string)(this["OptPathFirma2"]));
            }
            set {
                this["OptPathFirma2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlOptBazaKonfigConnectionStrFirma2 {
            get {
                return ((string)(this["SqlOptBazaKonfigConnectionStrFirma2"]));
            }
            set {
                this["SqlOptBazaKonfigConnectionStrFirma2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptModulyUseraFirma2 {
            get {
                return ((bool)(this["OptModulyUseraFirma2"]));
            }
            set {
                this["OptModulyUseraFirma2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptUserFirma2 {
            get {
                return ((string)(this["OptUserFirma2"]));
            }
            set {
                this["OptUserFirma2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptPasswordFirma2 {
            get {
                return ((string)(this["OptPasswordFirma2"]));
            }
            set {
                this["OptPasswordFirma2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptCompanyFirma2 {
            get {
                return ((string)(this["OptCompanyFirma2"]));
            }
            set {
                this["OptCompanyFirma2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlDatabaseName {
            get {
                return ((string)(this["SqlDatabaseName"]));
            }
            set {
                this["SqlDatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlServerName {
            get {
                return ((string)(this["SqlServerName"]));
            }
            set {
                this["SqlServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlLogin {
            get {
                return ((string)(this["SqlLogin"]));
            }
            set {
                this["SqlLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlPassword {
            get {
                return ((string)(this["SqlPassword"]));
            }
            set {
                this["SqlPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpecialOfferPriceTypeIdSFF {
            get {
                return ((int)(this["SpecialOfferPriceTypeIdSFF"]));
            }
            set {
                this["SpecialOfferPriceTypeIdSFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UpdAtrSaleIdSFF {
            get {
                return ((int)(this["UpdAtrSaleIdSFF"]));
            }
            set {
                this["UpdAtrSaleIdSFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdAtrSaleValueSFF {
            get {
                return ((string)(this["UpdAtrSaleValueSFF"]));
            }
            set {
                this["UpdAtrSaleValueSFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpecialOfferNameSFF {
            get {
                return ((string)(this["SpecialOfferNameSFF"]));
            }
            set {
                this["SpecialOfferNameSFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePathSFF {
            get {
                return ((string)(this["FilePathSFF"]));
            }
            set {
                this["FilePathSFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/26/2023 18:22:00")]
        public global::System.DateTime SpecialOfferFrom {
            get {
                return ((global::System.DateTime)(this["SpecialOfferFrom"]));
            }
            set {
                this["SpecialOfferFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/26/2023 18:22:00")]
        public global::System.DateTime SpecialOfferTo {
            get {
                return ((global::System.DateTime)(this["SpecialOfferTo"]));
            }
            set {
                this["SpecialOfferTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal OrderRotationDaysBack {
            get {
                return ((decimal)(this["OrderRotationDaysBack"]));
            }
            set {
                this["OrderRotationDaysBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OrderRotationMag {
            get {
                return ((int)(this["OrderRotationMag"]));
            }
            set {
                this["OrderRotationMag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OrderRotaionProductName {
            get {
                return ((string)(this["OrderRotaionProductName"]));
            }
            set {
                this["OrderRotaionProductName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OrderRotationAtrProductValue {
            get {
                return ((string)(this["OrderRotationAtrProductValue"]));
            }
            set {
                this["OrderRotationAtrProductValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OrderRotationAtrProductId {
            get {
                return ((int)(this["OrderRotationAtrProductId"]));
            }
            set {
                this["OrderRotationAtrProductId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OrderRotationKnt {
            get {
                return ((string)(this["OrderRotationKnt"]));
            }
            set {
                this["OrderRotationKnt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal OrderRotationAddIfZero {
            get {
                return ((decimal)(this["OrderRotationAddIfZero"]));
            }
            set {
                this["OrderRotationAddIfZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal OrderRotationMinValue {
            get {
                return ((decimal)(this["OrderRotationMinValue"]));
            }
            set {
                this["OrderRotationMinValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal OrderRotationMaxValue {
            get {
                return ((decimal)(this["OrderRotationMaxValue"]));
            }
            set {
                this["OrderRotationMaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OrderRotationKntId {
            get {
                return ((int)(this["OrderRotationKntId"]));
            }
            set {
                this["OrderRotationKntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LastKntByOrder {
            get {
                return ((bool)(this["LastKntByOrder"]));
            }
            set {
                this["LastKntByOrder"] = value;
            }
        }
    }
}
